version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=my-trip
      - POSTGRES_USER=my-trip
      - POSTGRES_PASSWORD=mytrip-group1
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

